# -*- coding: UTF-8 -*-

SCENE_AUTO_STANDBY = 64
SCENE_PANIC = 65
SCENE_ENERGY_OVERLOAD = 66
SCENE_STANDBY = 67
SCENE_DEEP_OFF = 68
SCENE_SLEEPING = 69
SCENE_WAKEUP = 70
SCENE_PRESENT = 71
SCENE_ABSENT = 72
SCENE_DOOR_BELL = 73
SCENE_ALARM_1 = 74
SCENE_ROOM_WAKEUP = 75
SCENE_FIRE = 76
SCENE_ALARM_2 = 83
SCENE_ALARM_3 = 84
SCENE_ALARM_4 = 85
SCENE_WIND = 86
SCENE_NO_WIND = 87
SCENE_RAIN = 88
SCENE_NO_RAIN = 89
SCENE_HAIL = 90
SCENE_NO_HAIL = 91

SCENE_NAMES = {
    SCENE_AUTO_STANDBY: "AUTO_STANDBY",
    SCENE_PANIC: "PANIC",
    SCENE_ENERGY_OVERLOAD: "ENERGY_OVERLOAD",
    SCENE_STANDBY: "STANDBY",
    SCENE_DEEP_OFF: "DEEP_OFF",
    SCENE_SLEEPING: "SLEEPING",
    SCENE_WAKEUP: "WAKEUP",
    SCENE_PRESENT: "PRESENT",
    SCENE_ABSENT: "ABSENT",
    SCENE_DOOR_BELL: "DOOR_BELL",
    SCENE_FIRE: "FIRE",
    SCENE_ALARM_1: "ALARM_SIGNAL_1",
    SCENE_ROOM_WAKEUP: "ROOM_WAKEUP",
    SCENE_ALARM_2: "ALARM_SIGNAL_2",
    SCENE_ALARM_3: "ALARM_SIGNAL_3",
    SCENE_ALARM_4: "ALARM_SIGNAL_4",
    SCENE_WIND: "WIND",
    SCENE_NO_WIND: "NO_WIND",
    SCENE_RAIN: "RAIN",
    SCENE_NO_RAIN: "NO_RAIN",
    SCENE_HAIL: "HAIL",
    SCENE_NO_HAIL: "NO_HAIL",
}
