# -*- coding: UTF-8 -*-

SCENE_AUTO_STANDBY = 'AUTO_STANDBY'
SCENE_PANIC = 'PANIC'
SCENE_ENERGY_OVERLOAD = 'ENERGY_OVERLOAD'
SCENE_STANDBY = 'STANDBY'
SCENE_DEEP_OFF = 'DEEP_OFF'
SCENE_SLEEPING = 'SLEEPING'
SCENE_WAKEUP = 'WAKEUP'
SCENE_PRESENT = 'PRESENT'
SCENE_ABSENT = 'ABSENT'
SCENE_DOOR_BELL = 'DOOR_BELL'
SCENE_ALARM_SIGNAL = 'ALARM_SIGNAL'
SCENES = {
    SCENE_AUTO_STANDBY: 64,
    SCENE_PANIC: 65,
    SCENE_ENERGY_OVERLOAD: 66,
    SCENE_STANDBY: 67,
    SCENE_DEEP_OFF: 68,
    SCENE_SLEEPING: 69,
    SCENE_WAKEUP: 70,
    SCENE_PRESENT: 71,
    SCENE_ABSENT: 72,
    SCENE_DOOR_BELL: 73,
    SCENE_ALARM_SIGNAL: 74,
}
